### ISSUE TITLE
place helm in /usr/bin rather than /usr/sbin

### ISSUE THREAD

**Issue by DanielDent** [BaltoRepo/helm-linux-packages#1]
Thanks for the package!

https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/sbin.html

> Deciding what things go into "sbin" directories is simple: if a normal
> (not a system administrator) user will ever run it directly, then it
> must be placed in one of the "bin" directories. Ordinary users should
> not have to place any of the sbin directories in their path.

I think the correct place for the helm binary is /usr/bin instead of /usr/sbin. A user using helm is not necessarily a system administrator of the system on which they are using helm. They may be administering a remote cluster.

**Comment by mattfox** [comment]
That's a good point. Thanks. I'll update when there's a new Helm release. To avoid blowing up existing users, I'll put a symlink in /usr/sbin.
